language: bash

addons:
  apt:
    update: true

services:
  - docker

install:
  - docker build --tag page-rotator .
  - docker run --detach --publish 80:80 page-rotator

script:
  - wget http://localhost
